#ifndef CARDS_H
#define CARDS_H

#define HEARTS_4 "./cards/hearts-4.png"
#define DIAMONDS_5 "./cards/diamonds-5.png"
#define SPADES_2 "./cards/spades-2.png"
#define SPADES_8 "./cards/spades-8.png"
#define BACK1 "./cards/back1.png"
#define CLUBS_10 "./cards/clubs-10.png"
#define HEARTS_5 "./cards/hearts-5.png"
#define SPADES_12 "./cards/spades-12.png"
#define SPADES_1 "./cards/spades-1.png"
#define HEARTS_3 "./cards/hearts-3.png"
#define CLUBS_13 "./cards/clubs-13.png"
#define BACK2 "./cards/back2.png"
#define HEARTS_6 "./cards/hearts-6.png"
#define DIAMONDS_4 "./cards/diamonds-4.png"
#define HEARTS_2 "./cards/hearts-2.png"
#define BACK4 "./cards/back4.png"
#define DIAMONDS_8 "./cards/diamonds-8.png"
#define CLUBS_2 "./cards/clubs-2.png"
#define DIAMONDS_3 "./cards/diamonds-3.png"
#define SPADES_3 "./cards/spades-3.png"
#define SPADES_5 "./cards/spades-5.png"
#define HEARTS_8 "./cards/hearts-8.png"
#define SPADES_11 "./cards/spades-11.png"
#define HEARTS_9 "./cards/hearts-9.png"
#define SPADES_9 "./cards/spades-9.png"
#define DIAMONDS_2 "./cards/diamonds-2.png"
#define UNNE "./cards/unneeded"
#define CLUBS_1 "./cards/clubs-1.png"
#define DIAMONDS_9 "./cards/diamonds-9.png"
#define HEARTS_7 "./cards/hearts-7.png"
#define CLUBS_9 "./cards/clubs-9.png"
#define SPADES_6 "./cards/spades-6.png"
#define DIAMONDS_10 "./cards/diamonds-10.png"
#define CLUBS_3 "./cards/clubs-3.png"
#define BLANK "./cards/blank.png"
#define SPADES_4 "./cards/spades-4.png"
#define CLUBS_6 "./cards/clubs-6.png"
#define BACK3 "./cards/back3.png"
#define DIAMONDS_6 "./cards/diamonds-6.png"
#define DIAMONDS_7 "./cards/diamonds-7.png"
#define CLUBS_5 "./cards/clubs-5.png"
#define SPADES_10 "./cards/spades-10.png"
#define CLUBS_8 "./cards/clubs-8.png"
#define SPADES_7 "./cards/spades-7.png"
#define CLUBS_4 "./cards/clubs-4.png"
#define CLUBS_11 "./cards/clubs-11.png"
#define CLUBS_12 "./cards/clubs-12.png"
#define SPADES_13 "./cards/spades-13.png"
#define HEARTS_10 "./cards/hearts-10.png"
#define CLUBS_7 "./cards/clubs-7.png"

#define DECK_SIZE 45

#endif

int initialise_deck();